name: publish-docs
on:
  push:
    branches: [master]
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry
          key: poetry-3.6-${{ hashFiles('poetry.lock', 'pyproject.toml') }}
          restore-keys: poetry-3.6-

      - name: Install App and Dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        # checks should install the local versions not, what's currently released
        run: poetry install --extras "env_setup run_tests build_docs"

      - name: Build Docs
        run: poetry run build-docs

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
